//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int Order_Item_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Food_Item_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual Food_Item Food_Items { get; set; }
        public virtual Order Order { get; set; }
    }
}
