//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Items = new HashSet<Order_Item>();
        }
    
        public int Order_Id { get; set; }
        public int Customer_Id { get; set; }
        public bool Submit_Status { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public Nullable<int> Food_Store_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public bool isActive { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Food_Store Food_Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Items { get; set; }
    }
}
