
//=============================================
//  Developer:	<Subin Sunu Jacob>
//  Create date: <14th May,2020>
//  Related To : To recieve all application related exceptions
//=============================================


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace OnlineFoodOrderingSystem.ExceptionLayer
{
    /// <summary>
    /// Custom Exception class for recieving all exceptions related to employee model
    /// </summary>
    public class EmployeeException : ApplicationException
    {
        /// <summary>
        /// recieves the exception generated by the application in employees model
        /// </summary>
        public EmployeeException()
        {
        }

        /// <summary>
        /// Recieves the exception generated along with the message the exception carried
        /// </summary>
        /// <param name="message">exception message that was generated and then passed along</param>
        public EmployeeException(string message) : base(message)
        {
        }

    }
}